// ─────────────────────────────────────────────────────────────
// seedData – Garage Auto Supplies High-Ticket CRM Seed Data
// ─────────────────────────────────────────────────────────────
import type { Lead } from '../types/lead';
import type { Deal, Task, LeadEvent, LeadNote } from '../types/crm';

export const SEED_LEADS: Lead[] = [
  // 1. Hot car lift quote
  {
    id: 'lead-101',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'm.vance@vancemotorsports.com',
    phone: '(310) 555-0192',
    company: 'Vance Motorsports & Custom Works',
    deliveryZip: '90210',
    productCategory: 'Car Lifts',
    category: 'Car Lifts',
    quantity: 2,
    targetBudget: '$34,500',
    productPrice: 34500,
    estimatedDealValue: 34500,
    projectDetails: 'Expanding our performance shop with two heavy-duty 4-post alignment bays. Need immediate delivery and turnkey installation before upcoming racing season.',
    source: {
      utm_source: 'google',
      utm_medium: 'cpc',
      utm_campaign: 'high_ticket_lifts_q3',
      landing_page: '/commercial-lifts',
    },
    score: 96,
    leadScore: 96,
    scoreBreakdown: {
      budgetScore: 35,
      categoryScore: 25,
      intentScore: 20,
      engagementScore: 16,
    },
    tier: 'hot',
    stage: 'negotiation',
    status: 'negotiation',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() - 3600 * 1000 * 2), // Overdue
    slaDeadlineAt: new Date(Date.now() - 3600 * 1000 * 2),
    slaStatus: 'overdue',
    isOverdue: true,
    contactedAt: null,
    lastContactedAt: null,
    formType: 'quote',
    shopifyCustomerId: 'cust_shop_99182',
    aiSummary: 'High intent buyer with verified commercial racing facility. Budget exceeds standard list price; requested expedited freight.',
    aiNextAction: 'Call Marcus immediately at (310) 555-0192 to confirm floor slab thickness and lock in freight schedule.',
    tags: ['car-lifts', 'hot', 'expedited', 'racing-facility'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 6),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 2),
    timeline: 'Immediate / Within 2 weeks',
  },
  // 2. Commercial Paint Booth
  {
    id: 'lead-102',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena@apexautocraft.io',
    phone: '(415) 555-8834',
    company: 'Apex Auto Craft & Restoration',
    deliveryZip: '94107',
    productCategory: 'Other Heavy Equipment',
    category: 'Other Heavy Equipment',
    productTitle: 'Commercial Paint Booth & Baking Oven',
    quantity: 1,
    targetBudget: '$62,000',
    productPrice: 62000,
    estimatedDealValue: 62000,
    projectDetails: 'Upgrading existing paint shop to meet California EPA downdraft regulations. Need full air makeup unit and LED lighting package.',
    source: {
      utm_source: 'referral',
      utm_medium: 'partner',
      referrer: 'shopownersassociation.com',
    },
    score: 92,
    leadScore: 92,
    scoreBreakdown: {
      budgetScore: 35,
      categoryScore: 25,
      intentScore: 18,
      engagementScore: 14,
    },
    tier: 'hot',
    stage: 'quoted',
    status: 'quoted',
    assignedTo: 'pablo-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 4),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 4),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 1),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 1),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Commercial body shop upgrading to compliance downdraft booth. Highly qualified, decision maker is owner.',
    aiNextAction: 'Send updated CAD floor layout and schedule video walkthrough with engineer.',
    tags: ['paint-booth', 'hot', 'epa-compliance'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 18),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 1),
    timeline: 'Within 30 days',
  },
  // 3. Fleet multi-unit tire changer
  {
    id: 'lead-103',
    firstName: 'David',
    lastName: 'Kowalczyk',
    email: 'dk@midwestfleetops.com',
    phone: '(312) 555-4411',
    company: 'Midwest Freight & Fleet Services',
    deliveryZip: '60601',
    productCategory: 'Tire Changers',
    category: 'Tire Changers',
    productTitle: 'Heavy-Duty Tire Changer & Wheel Balancer Combo',
    quantity: 4,
    targetBudget: '$48,000',
    productPrice: 48000,
    estimatedDealValue: 48000,
    projectDetails: 'Replacing legacy tire equipment across 2 fleet maintenance hubs in Chicago. Requires mobile service capability.',
    source: {
      utm_source: 'linkedin',
      utm_medium: 'sponsored_inmail',
      utm_campaign: 'fleet_executives_midwest',
    },
    score: 84,
    leadScore: 84,
    scoreBreakdown: {
      budgetScore: 30,
      categoryScore: 22,
      intentScore: 18,
      engagementScore: 14,
    },
    tier: 'warm',
    stage: 'qualified',
    status: 'qualified',
    assignedTo: 'pablo-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 12),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 12),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 5),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 5),
    formType: 'product_inquiry',
    shopifyCustomerId: 'cust_shop_11204',
    aiSummary: 'Fleet director purchasing multi-unit combo packages for commercial truck hubs.',
    aiNextAction: 'Provide volume pricing tier discount and warranty extension sheet.',
    tags: ['tire-changers', 'fleet', 'multi-unit', 'warm'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 24),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 5),
    timeline: 'Within 60 days',
  },
  // 4. 2-Post Lifts Austin
  {
    id: 'lead-104',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah@precisioneuro.net',
    phone: '(512) 555-7721',
    company: 'Precision Euro Tuning ATX',
    deliveryZip: '78701',
    productCategory: '2-Post Lifts',
    category: '2-Post Lifts',
    productTitle: 'Rotary 2-Post Asymmetrical Lift (10,000 lb)',
    quantity: 3,
    targetBudget: '$18,500',
    productPrice: 18500,
    estimatedDealValue: 18500,
    projectDetails: 'Opening third location in Austin. Looking for reliable 2-post lifts with quick-cycle hydraulic power units.',
    source: {
      utm_source: 'google',
      utm_medium: 'organic',
    },
    score: 78,
    leadScore: 78,
    scoreBreakdown: {
      budgetScore: 25,
      categoryScore: 20,
      intentScore: 18,
      engagementScore: 15,
    },
    tier: 'warm',
    stage: 'contacted',
    status: 'contacted',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() - 3600 * 1000 * 5),
    slaDeadlineAt: new Date(Date.now() - 3600 * 1000 * 5),
    slaStatus: 'warning',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 10),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 10),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Growing European auto specialist in Austin adding 3 bays.',
    aiNextAction: 'Follow up on formal proposal sent on Tuesday.',
    tags: ['2-post-lifts', 'warm', 'austin'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 48),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 10),
    timeline: 'Within 30 days',
  },
  // 5. Residential storage lift
  {
    id: 'lead-105',
    firstName: 'Bradley',
    lastName: 'Thornton',
    email: 'bthornton@gmail.com',
    phone: '(602) 555-3910',
    company: 'Personal Home Garage',
    deliveryZip: '85001',
    productCategory: '4-Post Lifts',
    category: '4-Post Lifts',
    productTitle: 'Residential Single-Post Storage Lift',
    quantity: 1,
    targetBudget: '$4,200',
    productPrice: 4200,
    estimatedDealValue: 4200,
    projectDetails: 'Looking for a basic storage lift for my residential garage in Phoenix.',
    source: {
      utm_source: 'facebook',
      utm_medium: 'social',
    },
    score: 42,
    leadScore: 42,
    scoreBreakdown: {
      budgetScore: 10,
      categoryScore: 12,
      intentScore: 10,
      engagementScore: 10,
    },
    tier: 'cold',
    stage: 'new',
    status: 'new',
    assignedTo: null,
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 36),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 36),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: null,
    lastContactedAt: null,
    formType: 'contact',
    shopifyCustomerId: null,
    aiSummary: 'Residential consumer inquiry with lower budget threshold.',
    aiNextAction: 'Send automated consumer brochure and self-serve checkout link.',
    tags: ['residential', 'cold', 'storage-lift'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 72),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 72),
    timeline: 'Next 90 days',
  },
  // 6. Won deal
  {
    id: 'lead-106',
    firstName: 'Travis',
    lastName: 'Colt',
    email: 'tcolt@coltmotors.com',
    phone: '(303) 555-9012',
    company: 'Colt Heavy Duty Diesel Service',
    deliveryZip: '80202',
    productCategory: 'Car Lifts',
    category: 'Car Lifts',
    productTitle: 'Mobile Column Lift System (72,000 lb set of 6)',
    quantity: 1,
    targetBudget: '$58,000',
    productPrice: 58000,
    estimatedDealValue: 58000,
    wonRevenue: 58000,
    projectDetails: 'Need wireless mobile column lifts for municipal bus maintenance contracts. Must be certified ALI approved.',
    source: {
      utm_source: 'google',
      utm_medium: 'cpc',
      utm_campaign: 'heavy_duty_mobile_columns',
    },
    score: 95,
    leadScore: 95,
    scoreBreakdown: {
      budgetScore: 35,
      categoryScore: 25,
      intentScore: 20,
      engagementScore: 15,
    },
    tier: 'hot',
    stage: 'won',
    status: 'won',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 20),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 20),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 90),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 90),
    formType: 'quote',
    shopifyCustomerId: 'cust_shop_88201',
    aiSummary: 'Municipal contractor locked in contract for mobile column lifts. Wire transfer received.',
    aiNextAction: 'Coordinate logistics delivery with Denver freight terminal.',
    tags: ['car-lifts', 'hot', 'ali-certified', 'won'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 120),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 12),
    timeline: 'Completed',
  },
  // 7. Lost deal
  {
    id: 'lead-107',
    firstName: 'Greg',
    lastName: 'House',
    email: 'greg@diagnosticmotors.com',
    phone: '(206) 555-3311',
    company: 'Diagnostic Specialty Garage',
    deliveryZip: '98101',
    productCategory: 'Pressure Washers',
    category: 'Pressure Washers',
    productTitle: 'Commercial Pressure Washer & Hot Water Steam Clean Bay',
    quantity: 1,
    targetBudget: '$11,500',
    productPrice: 11500,
    estimatedDealValue: 11500,
    lostReason: 'Price too high / Went with competitor who offered local plumbing installation',
    projectDetails: 'Installing an undercarriage cleaning bay. Need commercial steam clean package.',
    source: {
      utm_source: 'direct',
    },
    score: 65,
    leadScore: 65,
    scoreBreakdown: {
      budgetScore: 20,
      categoryScore: 18,
      intentScore: 15,
      engagementScore: 12,
    },
    tier: 'cold',
    stage: 'lost',
    status: 'lost',
    assignedTo: 'pablo-test-uid',
    slaDeadline: new Date(Date.now() - 3600 * 1000 * 40),
    slaDeadlineAt: new Date(Date.now() - 3600 * 1000 * 40),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 100),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 100),
    formType: 'product_inquiry',
    shopifyCustomerId: null,
    aiSummary: 'Customer went with local supplier due to plumbing contractor preference.',
    aiNextAction: 'Archive lead and add to 6-month check-in cadence.',
    tags: ['pressure-washers', 'lost'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 140),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 40),
    timeline: 'Lost',
  },
  // 8. Tire changer and wheel balancer package
  {
    id: 'lead-108',
    firstName: 'Carlos',
    lastName: 'Rodriguez',
    email: 'carlos@rodrigueztireshop.com',
    phone: '(305) 555-0162',
    company: 'Rodriguez Brothers Tire & Wheel',
    deliveryZip: '33101',
    productCategory: 'Tire Changers',
    category: 'Tire Changers',
    productTitle: 'Tire Changer & Wheel Balancer Combo Package',
    quantity: 1,
    targetBudget: '$8,500',
    productPrice: 8500,
    estimatedDealValue: 8500,
    projectDetails: 'We need a tilt-back tire changer with assist arm and computerized wheel balancer package for low profile and run-flat tires.',
    source: { utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'tire_combo_sale', gclid: 'EAIaIQobChMI_rodriguez_mock_04' },
    score: 72,
    leadScore: 72,
    scoreBreakdown: { budgetScore: 22, categoryScore: 20, intentScore: 18, engagementScore: 12 },
    tier: 'warm',
    stage: 'contacted',
    status: 'contacted',
    assignedTo: 'sales-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 15),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 15),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 3),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 3),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Tire shop owner replacing aging equipment with high-performance combo package.',
    aiNextAction: 'Send video demonstration of assist arm handling run-flat tires.',
    tags: ['tire-changers', 'wheel-balancers', 'warm'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 20),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 3),
    timeline: 'Within 30 days',
  },
  // 9. Mini excavator quote
  {
    id: 'lead-109',
    firstName: 'David',
    lastName: 'Miller',
    email: 'dmiller@millerheavyrepair.com',
    phone: '(720) 555-0144',
    company: 'Miller Heavy Diesel Repair',
    deliveryZip: '80014',
    productCategory: 'Mini Excavators',
    category: 'Mini Excavators',
    productTitle: '3.5-Ton Mini Excavator with Enclosed Cab',
    quantity: 1,
    targetBudget: '$28,000',
    productPrice: 28000,
    estimatedDealValue: 28000,
    projectDetails: 'Looking for a 3.5-ton mini excavator with hydraulic thumb and enclosed cab for our mobile excavation unit.',
    source: { utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'heavy_excavators_exact', gclid: 'EAIaIQobChMI_miller_mock_gclid_02' },
    score: 88,
    leadScore: 88,
    scoreBreakdown: { budgetScore: 30, categoryScore: 25, intentScore: 18, engagementScore: 15 },
    tier: 'hot',
    stage: 'quoted',
    status: 'quoted',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 8),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 8),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 4),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 4),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Commercial diesel repair contractor buying mini excavator for site prep.',
    aiNextAction: 'Follow up on spec sheet sent yesterday and confirm warranty terms.',
    tags: ['mini-excavators', 'hot'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 30),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4),
    timeline: 'Immediate',
  },
  // 10. Pressure washer commercial buyer
  {
    id: 'lead-110',
    firstName: 'Kevin',
    lastName: 'Patel',
    email: 'kpatel@expresscarwashpros.com',
    phone: '(713) 555-0149',
    company: 'Express Car Wash Pros',
    deliveryZip: '77002',
    productCategory: 'Pressure Washers',
    category: 'Pressure Washers',
    productTitle: 'Hot-Water Diesel Commercial Pressure Washers (4000 PSI)',
    quantity: 2,
    targetBudget: '$6,000',
    productPrice: 6000,
    estimatedDealValue: 6000,
    projectDetails: 'Need two hot-water diesel heated commercial pressure washers (4000 PSI / 4.0 GPM) for our detailing bays.',
    source: { utm_source: 'direct' },
    score: 68,
    leadScore: 68,
    scoreBreakdown: { budgetScore: 20, categoryScore: 20, intentScore: 16, engagementScore: 12 },
    tier: 'warm',
    stage: 'qualified',
    status: 'qualified',
    assignedTo: 'sales-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 20),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 20),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 12),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 12),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Car wash chain owner expanding detailing operations in Houston.',
    aiNextAction: 'Send commercial invoice with bundle discount for two units.',
    tags: ['pressure-washers', 'warm', 'commercial-buyer'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 50),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 12),
    timeline: 'Within 30 days',
  },
  // 11. Generator inquiry
  {
    id: 'lead-111',
    firstName: 'Bruce',
    lastName: 'Wayne',
    email: 'bruce@wayneenterprisesmotorpool.com',
    phone: '(312) 555-0190',
    company: 'Wayne Motorpool Division',
    deliveryZip: '60601',
    productCategory: 'Generators',
    category: 'Generators',
    productTitle: '15,000W Tri-Fuel Industrial Generator',
    quantity: 1,
    targetBudget: '$3,500',
    productPrice: 3500,
    estimatedDealValue: 3500,
    projectDetails: 'Inquiring about a backup 15,000 Watt industrial tri-fuel generator with automatic transfer switch.',
    source: { utm_source: 'direct' },
    score: 38,
    leadScore: 38,
    scoreBreakdown: { budgetScore: 10, categoryScore: 10, intentScore: 10, engagementScore: 8 },
    tier: 'cold',
    stage: 'new',
    status: 'new',
    assignedTo: null,
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 24),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 24),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: null,
    lastContactedAt: null,
    formType: 'contact',
    shopifyCustomerId: null,
    aiSummary: 'Corporate inquiry regarding emergency power generation.',
    aiNextAction: 'Send generator spec sheet and commercial warranty catalog.',
    tags: ['generators', 'cold', 'inquiry'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 14),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 14),
    timeline: 'Next quarter',
  },
  // 12. Full garage shop package
  {
    id: 'lead-112',
    firstName: 'Robert',
    lastName: 'Chen',
    email: 'rchen@apexmotorgarage.com',
    phone: '(415) 555-0188',
    company: 'Apex Motor Garage',
    deliveryZip: '94103',
    productCategory: 'Car Lifts',
    category: 'Car Lifts',
    productTitle: 'Full Luxury Garage Shop Package (Lifts, Storage, Compressors)',
    quantity: 5,
    targetBudget: '$45,000',
    productPrice: 45000,
    estimatedDealValue: 45000,
    projectDetails: 'Opening a new luxury storage vehicle facility. Need 3 high-clearance storage car lifts, modular steel cabinets, and a rotary screw compressor. Full shop package.',
    source: { utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'storage_lifts_pro', gclid: 'EAIaIQobChMI_chen_mock_gclid_03' },
    score: 95,
    leadScore: 95,
    scoreBreakdown: { budgetScore: 35, categoryScore: 25, intentScore: 20, engagementScore: 15 },
    tier: 'hot',
    stage: 'negotiation',
    status: 'negotiation',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 10),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 10),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 18),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 18),
    formType: 'quote',
    shopifyCustomerId: 'cust_shop_77210',
    aiSummary: 'Turnkey new garage setup in San Francisco. High dollar value package deal.',
    aiNextAction: 'Review package discount and schedule on-site installation assessment.',
    tags: ['car-lifts', 'garage-storage', 'air-compressors', 'hot', 'full-package'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 60),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 18),
    timeline: 'Immediate / Same week',
  },
  // 13. Price match request
  {
    id: 'lead-113',
    firstName: 'Thomas',
    lastName: 'Wright',
    email: 'twright@wrightlandscaping.net',
    phone: '(404) 555-0128',
    company: 'Wright Pro Automotive & Fleet',
    deliveryZip: '30301',
    productCategory: '2-Post Lifts',
    category: '2-Post Lifts',
    productTitle: '10,000 lb 2-Post Commercial Lift (Price Match Request)',
    quantity: 1,
    targetBudget: '$4,200',
    productPrice: 4200,
    estimatedDealValue: 4200,
    projectDetails: 'We found a competitor lift (BendPak 10AP) quoted for $3,900 including freight. Can you price match or beat their quote for your Rotary 10k equivalent?',
    source: { utm_source: 'google', utm_medium: 'cpc', utm_campaign: '2_post_lifts_competitor' },
    score: 66,
    leadScore: 66,
    scoreBreakdown: { budgetScore: 20, categoryScore: 20, intentScore: 16, engagementScore: 10 },
    tier: 'warm',
    stage: 'contacted',
    status: 'contacted',
    assignedTo: 'sales-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 12),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 12),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 6),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 6),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Customer ready to buy today if we match competitor pricing of $3,900.',
    aiNextAction: 'Offer $3,950 with free heavy-duty truck adapter kit to close the deal.',
    tags: ['2-post-lifts', 'warm', 'price-match'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 24),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 6),
    timeline: 'Immediate / This week',
  },
  // 14. Financing interest
  {
    id: 'lead-114',
    firstName: 'Amanda',
    lastName: 'Foster',
    email: 'afoster@fostercollision.com',
    phone: '(602) 555-0137',
    company: 'Foster Auto Collision & Body',
    deliveryZip: '85001',
    productCategory: 'Scissor Lifts',
    category: 'Scissor Lifts',
    productTitle: 'Mid-Rise Mobile Scissor Lift (36-Month Financing Inquiry)',
    quantity: 1,
    targetBudget: '$9,000',
    productPrice: 9000,
    estimatedDealValue: 9000,
    projectDetails: 'Interested in two mid-rise mobile scissor lifts for bodywork and paint prep. We would like to apply for your 36-month 0% commercial equipment financing program.',
    source: { utm_source: 'google', utm_medium: 'cpc', gclid: 'EAIaIQobChMI_foster_mock_05' },
    score: 70,
    leadScore: 70,
    scoreBreakdown: { budgetScore: 25, categoryScore: 20, intentScore: 15, engagementScore: 10 },
    tier: 'warm',
    stage: 'new',
    status: 'new',
    assignedTo: null,
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 18),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 18),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: null,
    lastContactedAt: null,
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Collision shop inquiring specifically about equipment financing application.',
    aiNextAction: 'Send commercial financing application link and equipment spec sheets.',
    tags: ['scissor-lifts', 'warm', 'financing'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 8),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 8),
    timeline: 'Within 30 days',
  },
  // 15. No phone weak lead
  {
    id: 'lead-115',
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe_garage@gmail.com',
    phone: undefined,
    company: 'Personal Home Garage',
    deliveryZip: '84101',
    productCategory: 'Garage Storage',
    category: 'Garage Storage',
    productTitle: 'Residential Steel Modular Storage Cabinets',
    quantity: 1,
    targetBudget: '$1,200',
    productPrice: 1200,
    estimatedDealValue: 1200,
    projectDetails: 'Want to organize my 3-car residential garage. Interested in steel modular storage cabinets. No phone calls please, email only.',
    source: { utm_source: 'direct' },
    score: 25,
    leadScore: 25,
    scoreBreakdown: { budgetScore: 8, categoryScore: 8, intentScore: 5, engagementScore: 4 },
    tier: 'cold',
    stage: 'new',
    status: 'new',
    assignedTo: null,
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 48),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 48),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: null,
    lastContactedAt: null,
    formType: 'product_inquiry',
    shopifyCustomerId: null,
    aiSummary: 'Low budget residential buyer who omitted phone number and requested email only.',
    aiNextAction: 'Send automated storage catalog email with online store discount code.',
    tags: ['garage-storage', 'cold', 'no-phone', 'weak-lead'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 10),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 10),
    timeline: 'Unsure',
  },
  // 16. Bad fit lead
  {
    id: 'lead-116',
    firstName: 'Clark',
    lastName: 'Kent',
    email: 'ckent@smallvillecycling.org',
    phone: '(316) 555-0140',
    company: 'Smallville Bike & Hobby',
    deliveryZip: '67201',
    productCategory: 'Other Heavy Equipment',
    category: 'Other Heavy Equipment',
    productTitle: 'Residential Bicycle Wall Hanging Racks',
    quantity: 1,
    targetBudget: '$800',
    productPrice: 800,
    estimatedDealValue: 800,
    lostReason: 'Looking for residential bicycle hanging racks / not commercial automotive equipment (Bad fit)',
    projectDetails: 'Do you carry residential wall-mounted bicycle hanging racks for garage ceilings?',
    source: { utm_source: 'google', utm_medium: 'organic' },
    score: 15,
    leadScore: 15,
    scoreBreakdown: { budgetScore: 5, categoryScore: 4, intentScore: 3, engagementScore: 3 },
    tier: 'cold',
    stage: 'lost',
    status: 'lost',
    assignedTo: 'sales-test-uid',
    slaDeadline: new Date(Date.now() - 3600 * 1000 * 10),
    slaDeadlineAt: new Date(Date.now() - 3600 * 1000 * 10),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 40),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 40),
    formType: 'product_inquiry',
    shopifyCustomerId: null,
    aiSummary: 'Bad fit inquiry: consumer seeking bicycle storage racks which we do not sell.',
    aiNextAction: 'Mark as lost (Bad Fit) and remove from active sales cadence.',
    tags: ['bad-fit', 'lost', 'other'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 100),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 40),
    timeline: 'None',
  },
  // 17. Google Ads lead with gclid
  {
    id: 'lead-117',
    firstName: 'Brian',
    lastName: 'OConnor',
    email: 'brian@oconnorcustoms.com',
    phone: '(213) 555-0119',
    company: 'OConnor Speed Shop & Alignment',
    deliveryZip: '90015',
    productCategory: '4-Post Lifts',
    category: '4-Post Lifts',
    productTitle: 'Commercial Alignment 4-Post Lift Package',
    quantity: 1,
    targetBudget: '$16,500',
    productPrice: 16500,
    estimatedDealValue: 16500,
    projectDetails: 'Looking for an extra wide 4-post alignment lift with slip plates and rolling hydraulic jacks for our LA tuning shop.',
    source: {
      utm_source: 'google',
      utm_medium: 'cpc',
      utm_campaign: 'alignment_lifts_search_la',
      gclid: 'EAIaIQobChMI_oconnor_mock_gclid_99',
    },
    gclid: 'EAIaIQobChMI_oconnor_mock_gclid_99',
    score: 86,
    leadScore: 86,
    scoreBreakdown: { budgetScore: 30, categoryScore: 25, intentScore: 18, engagementScore: 13 },
    tier: 'hot',
    stage: 'quoted',
    status: 'quoted',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 6),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 6),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 14),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 14),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Google Ads high-intent conversion with verified gclid tracking. Ready for alignment equipment.',
    aiNextAction: 'Review quote sent yesterday and confirm turn-table dimensions.',
    tags: ['4-post-lifts', 'hot', 'google-ads', 'gclid'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 36),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 14),
    timeline: 'Within 14 days',
  },
  // 18. Urgent same-week buyer
  {
    id: 'lead-118',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sjenkins@jenkinsfleet.org',
    phone: '(816) 555-0177',
    company: 'Jenkins Municipal Fleet Services',
    deliveryZip: '64106',
    productCategory: '2-Post Lifts',
    category: '2-Post Lifts',
    productTitle: '4x 12,000 lb 2-Post Heavy-Duty Lifts (URGENT Delivery)',
    quantity: 4,
    targetBudget: '$25,000',
    productPrice: 25000,
    estimatedDealValue: 25000,
    projectDetails: 'City fleet maintenance upgrade. We need four 12,000 lb 2-post lifts with symmetric arms. URGENT: Government PO approved, need delivery and install THIS WEEK before fiscal quarter close.',
    source: { utm_source: 'direct', referrer: '' },
    score: 94,
    leadScore: 94,
    scoreBreakdown: { budgetScore: 35, categoryScore: 25, intentScore: 20, engagementScore: 14 },
    tier: 'hot',
    stage: 'qualified',
    status: 'qualified',
    assignedTo: 'ben-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 2),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 2),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 4),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 4),
    formType: 'quote',
    shopifyCustomerId: 'cust_shop_55102',
    aiSummary: 'Government municipal fleet buyer with emergency same-week deadline and approved PO.',
    aiNextAction: 'Coordinate immediate warehouse dispatch and reserve installation crew for Friday.',
    tags: ['2-post-lifts', 'hot', 'urgent', 'same-week-buyer', 'municipal'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 24),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4),
    timeline: 'Immediate / Same week',
  },
  // 19. Quantity 3+ buyer
  {
    id: 'lead-119',
    firstName: 'Jason',
    lastName: 'Kowalski',
    email: 'jasonk@timberlandlogging.com',
    phone: '(503) 555-0133',
    company: 'Timberland Logging & Timber',
    deliveryZip: '97201',
    productCategory: 'Sawmills',
    category: 'Sawmills',
    productTitle: '3x Commercial Portable Band Sawmills (25HP Engine)',
    quantity: 3,
    targetBudget: '$36,000',
    productPrice: 36000,
    estimatedDealValue: 36000,
    projectDetails: 'Need three commercial portable band sawmills with hydraulic log loaders and 25HP Kohler engines for our Oregon timber camps. Multi-unit quantity discount requested.',
    source: { utm_source: 'google', utm_medium: 'organic', landing_page: '/products/commercial-portable-sawmill-25hp' },
    score: 89,
    leadScore: 89,
    scoreBreakdown: { budgetScore: 30, categoryScore: 24, intentScore: 20, engagementScore: 15 },
    tier: 'hot',
    stage: 'negotiation',
    status: 'negotiation',
    assignedTo: 'pablo-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 10),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 10),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 8),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 8),
    formType: 'quote',
    shopifyCustomerId: null,
    aiSummary: 'Multi-unit logging company purchasing 3 commercial sawmills simultaneously.',
    aiNextAction: 'Send revised contract with 7% volume discount and free replacement bandsaw blades.',
    tags: ['sawmills', 'hot', 'quantity-3plus', 'multi-unit'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 40),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 8),
    timeline: 'Within 30 days',
  },
  // 20. Stump Grinders
  {
    id: 'lead-120',
    firstName: 'Derek',
    lastName: 'Hale',
    email: 'dhale@haletreecare.com',
    phone: '(512) 555-0181',
    company: 'Hale Tree & Stump Specialists',
    deliveryZip: '78701',
    productCategory: 'Stump Grinders',
    category: 'Stump Grinders',
    productTitle: '15HP Track-Driven Commercial Stump Grinder',
    quantity: 1,
    targetBudget: '$5,500',
    productPrice: 5500,
    estimatedDealValue: 5500,
    projectDetails: 'Interested in the 15HP track-driven stump grinder for our Austin tree removal service.',
    source: { utm_source: 'google', utm_medium: 'organic' },
    score: 64,
    leadScore: 64,
    scoreBreakdown: { budgetScore: 20, categoryScore: 18, intentScore: 14, engagementScore: 12 },
    tier: 'warm',
    stage: 'contacted',
    status: 'contacted',
    assignedTo: 'sales-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 14),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 14),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 6),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 6),
    formType: 'product_inquiry',
    shopifyCustomerId: null,
    aiSummary: 'Tree care contractor looking for reliable track stump grinder.',
    aiNextAction: 'Send video link of track grinder operating on steep terrain.',
    tags: ['stump-grinders', 'warm'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 30),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 6),
    timeline: 'Within 30 days',
  },
  // 21. Sheet Metal Brakes
  {
    id: 'lead-121',
    firstName: 'Michael',
    lastName: 'Scott',
    email: 'mscott@scottsheetyandmetal.com',
    phone: '(570) 555-0111',
    company: 'Scott Sheet Metal & Fabrication',
    deliveryZip: '18503',
    productCategory: 'Sheet Metal Brakes',
    category: 'Sheet Metal Brakes',
    productTitle: '10-Foot Magnetic Sheet Metal Brake',
    quantity: 1,
    targetBudget: '$3,800',
    productPrice: 3800,
    estimatedDealValue: 3800,
    projectDetails: 'Looking for a 10-foot magnetic sheet metal brake for HVAC ductwork and custom panels.',
    source: { utm_source: 'google', utm_medium: 'organic' },
    score: 55,
    leadScore: 55,
    scoreBreakdown: { budgetScore: 18, categoryScore: 15, intentScore: 12, engagementScore: 10 },
    tier: 'warm',
    stage: 'new',
    status: 'new',
    assignedTo: null,
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 16),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 16),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: null,
    lastContactedAt: null,
    formType: 'product_inquiry',
    shopifyCustomerId: null,
    aiSummary: 'HVAC sheet metal contractor inquiring about 10ft magnetic brake.',
    aiNextAction: 'Call to discuss bending gauge limits and shipping dimensions.',
    tags: ['sheet-metal-brakes', 'warm'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 12),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 12),
    timeline: 'Within 60 days',
  },
  // 22. Workbenches
  {
    id: 'lead-122',
    firstName: 'Peter',
    lastName: 'Parker',
    email: 'peter@dailybugleautofleet.com',
    phone: '(212) 555-0101',
    company: 'Bugle Courier Fleet Ops',
    deliveryZip: '10001',
    productCategory: 'Workbenches',
    category: 'Workbenches',
    productTitle: 'Heavy-Duty Steel Workbenches with Butcher Block Tops',
    quantity: 2,
    targetBudget: '$2,400',
    productPrice: 2400,
    estimatedDealValue: 2400,
    projectDetails: 'Need two heavy duty steel workbenches with butcher block tops and overhead LED lighting for vehicle repair shop.',
    source: { utm_source: 'google', utm_medium: 'organic' },
    score: 48,
    leadScore: 48,
    scoreBreakdown: { budgetScore: 15, categoryScore: 13, intentScore: 10, engagementScore: 10 },
    tier: 'cold',
    stage: 'contacted',
    status: 'contacted',
    assignedTo: 'sales-test-uid',
    slaDeadline: new Date(Date.now() + 3600 * 1000 * 30),
    slaDeadlineAt: new Date(Date.now() + 3600 * 1000 * 30),
    slaStatus: 'ok',
    isOverdue: false,
    contactedAt: new Date(Date.now() - 3600 * 1000 * 24),
    lastContactedAt: new Date(Date.now() - 3600 * 1000 * 24),
    formType: 'product_inquiry',
    shopifyCustomerId: null,
    aiSummary: 'Fleet maintenance shop adding two industrial workbenches.',
    aiNextAction: 'Send workbench assembly manual and accessories brochure.',
    tags: ['workbenches', 'cold'],
    createdAt: new Date(Date.now() - 3600 * 1000 * 70),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 24),
    timeline: 'Next quarter',
  },
];

export const SEED_DEALS: Deal[] = [
  {
    id: 'deal-201',
    title: 'Vance Motorsports - 2x 4-Post Lifts',
    leadId: 'lead-101',
    contactName: 'Marcus Vance',
    value: 34500,
    stage: 'negotiation',
    probability: 50,
    assignedTo: 'ben-test-uid',
    expectedCloseDate: new Date(Date.now() + 3600 * 1000 * 24 * 5),
    notes: 'Freight terms agreed. Waiting on CFO signature on final purchase agreement.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 48),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4),
  },
  {
    id: 'deal-202',
    title: 'Apex Auto Craft - EPA Downdraft Booth',
    leadId: 'lead-102',
    contactName: 'Elena Rostova',
    value: 62000,
    stage: 'proposal',
    probability: 30,
    assignedTo: 'pablo-test-uid',
    expectedCloseDate: new Date(Date.now() + 3600 * 1000 * 24 * 10),
    notes: 'CAD layout sent. Client reviewing ventilation specs with landlord.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 36),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 12),
  },
  {
    id: 'deal-203',
    title: 'Midwest Fleet - 4x Tire Changer Combo',
    leadId: 'lead-103',
    contactName: 'David Kowalczyk',
    value: 48000,
    stage: 'proposal',
    probability: 30,
    assignedTo: 'pablo-test-uid',
    expectedCloseDate: new Date(Date.now() + 3600 * 1000 * 24 * 14),
    notes: 'Contract out for review.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 72),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 8),
  },
  {
    id: 'deal-204',
    title: 'Colt Heavy Duty - Mobile Column System',
    leadId: 'lead-106',
    contactName: 'Travis Colt',
    value: 58000,
    stage: 'closed_won',
    probability: 100,
    assignedTo: 'ben-test-uid',
    expectedCloseDate: new Date(Date.now() - 3600 * 1000 * 24 * 1),
    notes: 'Wire transfer confirmed! Deal closed won.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 120),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 12),
  },
  {
    id: 'deal-205',
    title: 'OConnor Speed Shop - Alignment Package',
    leadId: 'lead-117',
    contactName: 'Brian OConnor',
    value: 16500,
    stage: 'proposal',
    probability: 30,
    assignedTo: 'ben-test-uid',
    expectedCloseDate: new Date(Date.now() + 3600 * 1000 * 24 * 7),
    notes: 'Google Ads conversion. Client comparing quote with BendPak.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 36),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 14),
  },
  {
    id: 'deal-206',
    title: 'Jenkins Fleet - 4x 2-Post Urgent PO',
    leadId: 'lead-118',
    contactName: 'Sarah Jenkins',
    value: 25000,
    stage: 'negotiation',
    probability: 75,
    assignedTo: 'ben-test-uid',
    expectedCloseDate: new Date(Date.now() + 3600 * 1000 * 24 * 2),
    notes: 'Government PO approved! Scheduling warehouse dispatch.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 24),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4),
  },
  {
    id: 'deal-207',
    title: 'Timberland Logging - 3x Portable Sawmills',
    leadId: 'lead-119',
    contactName: 'Jason Kowalski',
    value: 36000,
    stage: 'negotiation',
    probability: 50,
    assignedTo: 'pablo-test-uid',
    expectedCloseDate: new Date(Date.now() + 3600 * 1000 * 24 * 10),
    notes: 'Multi-unit 3+ buyer. Offered 7% volume discount.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 40),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 8),
  },
  {
    id: 'deal-208',
    title: 'Diagnostic Specialty - Pressure Washer',
    leadId: 'lead-107',
    contactName: 'Greg House',
    value: 11500,
    stage: 'closed_lost',
    probability: 0,
    assignedTo: 'pablo-test-uid',
    expectedCloseDate: new Date(Date.now() - 3600 * 1000 * 24 * 2),
    notes: 'Lost deal: Went with local plumbing contractor.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 140),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 40),
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: 'task-301',
    title: '⚡ URGENT: Call Marcus Vance - Overdue SLA',
    description: 'Lead inquiry is overdue by 2 hours! Need immediate phone outreach regarding 4-Post Lift package ($34,500).',
    leadId: 'lead-101',
    assignedTo: 'ben-test-uid',
    assignedBy: 'system',
    status: 'pending',
    priority: 'urgent',
    dueDate: new Date(Date.now() - 3600 * 1000 * 1),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600 * 1000 * 3),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 1),
  },
  {
    id: 'task-302',
    title: 'Review CAD ventilation layout for Apex Auto Craft',
    description: 'Ensure air makeup CFM calculations meet California EPA downdraft booth standards before meeting.',
    leadId: 'lead-102',
    assignedTo: 'pablo-test-uid',
    assignedBy: 'ben-test-uid',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date(Date.now() + 3600 * 1000 * 5),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600 * 1000 * 12),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 2),
  },
  {
    id: 'task-303',
    title: 'Send DocuSign reminder to David Kowalczyk',
    description: 'Follow up on the $48,000 tire changer combo contract.',
    leadId: 'lead-103',
    assignedTo: 'pablo-test-uid',
    assignedBy: 'pablo-test-uid',
    status: 'pending',
    priority: 'normal',
    dueDate: new Date(Date.now() + 3600 * 1000 * 24),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600 * 1000 * 18),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 5),
  },
  {
    id: 'task-304',
    title: 'Coordinate freight delivery for Colt Heavy Duty',
    description: 'Arrange lift gate drop off at Denver municipal terminal for 6 mobile column lifts.',
    leadId: 'lead-106',
    assignedTo: 'ben-test-uid',
    assignedBy: 'ben-test-uid',
    status: 'completed',
    priority: 'high',
    dueDate: new Date(Date.now() - 3600 * 1000 * 10),
    completedAt: new Date(Date.now() - 3600 * 1000 * 8),
    createdAt: new Date(Date.now() - 3600 * 1000 * 24),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 8),
  },
  {
    id: 'task-305',
    title: '⚡ URGENT: Dispatch 4x 2-Post Lifts for Jenkins Municipal',
    description: 'Government PO approved. Ensure warehouse packs symmetric arm kits for Friday delivery.',
    leadId: 'lead-118',
    assignedTo: 'ben-test-uid',
    assignedBy: 'system',
    status: 'pending',
    priority: 'urgent',
    dueDate: new Date(Date.now() + 3600 * 1000 * 6),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600 * 1000 * 4),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4),
  },
  {
    id: 'task-306',
    title: 'Call Thomas Wright regarding $3,900 Price Match',
    description: 'Confirm we can beat competitor BendPak quote with free heavy duty truck adapter kit.',
    leadId: 'lead-113',
    assignedTo: 'sales-test-uid',
    assignedBy: 'system',
    status: 'pending',
    priority: 'high',
    dueDate: new Date(Date.now() + 3600 * 1000 * 4),
    completedAt: null,
    createdAt: new Date(Date.now() - 3600 * 1000 * 6),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 6),
  },
];

export const SEED_EVENTS: Record<string, LeadEvent[]> = {
  'lead-101': [
    {
      id: 'evt-1',
      leadId: 'lead-101',
      type: 'score_updated',
      description: 'Lead score calculated as 96 (HOT Tier) via high-ticket scoring algorithm.',
      metadata: { score: 96, tier: 'hot', budget: '$34,500' },
      createdBy: 'AI Scoring Engine',
      createdAt: new Date(Date.now() - 3600 * 1000 * 6),
    },
    {
      id: 'evt-2',
      leadId: 'lead-101',
      type: 'deal_created',
      description: 'Created deal "Vance Motorsports - 2x 4-Post Lifts" ($34,500).',
      metadata: { dealId: 'deal-201', value: 34500 },
      createdBy: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 4),
    },
    {
      id: 'evt-3',
      leadId: 'lead-101',
      type: 'stage_changed',
      description: 'Moved pipeline stage from Quoted to Negotiation.',
      createdBy: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 2),
    },
  ],
  'lead-106': [
    {
      id: 'evt-106-1',
      leadId: 'lead-106',
      type: 'stage_changed',
      description: 'Lead closed WON! Revenue: $58,000.',
      metadata: { stage: 'won', wonRevenue: 58000 },
      createdBy: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 12),
    },
  ],
  'lead-107': [
    {
      id: 'evt-107-1',
      leadId: 'lead-107',
      type: 'stage_changed',
      description: 'Lead closed LOST. Reason: Went with competitor who offered local plumbing installation.',
      metadata: { stage: 'lost', lostReason: 'Price too high / Went with competitor' },
      createdBy: 'pablo-test-uid',
      createdAt: new Date(Date.now() - 3600 * 1000 * 40),
    },
  ],
  'lead-118': [
    {
      id: 'evt-118-1',
      leadId: 'lead-118',
      type: 'email_sent',
      description: 'Formal urgent quote sent with government municipal discount.',
      metadata: { stage: 'qualified' },
      createdBy: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 4),
    },
  ],
};

export const SEED_NOTES: Record<string, LeadNote[]> = {
  'lead-101': [
    {
      id: 'note-1',
      leadId: 'lead-101',
      content: 'Spoke with Marcus regarding freight requirements. He needs custom low-profile ramps for lowered GT3 RS race cars. Added optional ramp extensions to formal quote.',
      createdBy: 'ben-test-uid',
      createdByName: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 5),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 5),
    },
    {
      id: 'note-2',
      leadId: 'lead-101',
      content: 'CFO requested W-9 form and bank ACH wire instructions. Emailed package to accounting@vancemotorsports.com.',
      createdBy: 'ben-test-uid',
      createdByName: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 3),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 3),
    },
  ],
  'lead-113': [
    {
      id: 'note-113-1',
      leadId: 'lead-113',
      content: 'Verified competitor BendPak quote. We can offer $3,950 and throw in the $180 truck adapter kit free of charge to win the order.',
      createdBy: 'sales-test-uid',
      createdByName: 'Sam Sales Rep',
      createdAt: new Date(Date.now() - 3600 * 1000 * 6),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 6),
    },
  ],
  'lead-118': [
    {
      id: 'note-118-1',
      leadId: 'lead-118',
      content: 'Jenkins Fleet municipal PO #GF-99182 received. Expedited freight booked via Yellow Freight.',
      createdBy: 'ben-test-uid',
      createdByName: 'Ben (Clutch King)',
      createdAt: new Date(Date.now() - 3600 * 1000 * 4),
      updatedAt: new Date(Date.now() - 3600 * 1000 * 4),
    },
  ],
};
