// ─────────────────────────────────────────────────────────────
// Task Types – Garage Auto Supplies CRM
// ─────────────────────────────────────────────────────────────

/** Kind of follow-up action */
export type TaskType = 'follow_up' | 'call' | 'email' | 'quote' | 'general';

/** Urgency level */
export type TaskPriority = 'urgent' | 'high' | 'normal' | 'low';

/** Lifecycle status */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled';

/** Task / action item linked to a Lead */
export interface Task {
  id: string;
  leadId: string;
  title: string;
  description: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dueAt: Date;
  assignedTo: string;
  /** True when the task was auto-created by SLA or AI logic */
  isAutoGenerated: boolean;
  completedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}
