import * as functions from 'firebase-functions';
import { admin, db } from '../firebaseAdmin';

/**
 * Scheduled function: SLA Checker
 * Runs every 5 minutes during business hours.
 *
 * Checks all leads where:
 * - slaStatus is NOT 'overdue'
 * - contactedAt is null (not yet contacted)
 * - slaDeadline has passed
 *
 * Marks them as overdue and creates alert tasks.
 */
export const slaChecker = functions.pubsub
  .schedule('every 5 minutes')
  .timeZone('America/New_York')
  .onRun(async () => {
    const now = admin.firestore.Timestamp.now();

    try {
      // Find leads that are past their SLA deadline but not yet marked overdue
      const snapshot = await db
        .collection('leads')
        .where('slaStatus', 'in', ['ok', 'warning'])
        .where('contactedAt', '==', null)
        .where('slaDeadline', '<=', now)
        .get();

      if (snapshot.empty) {
        functions.logger.info('SLA check: No overdue leads found');
        return null;
      }

      const batch = db.batch();
      let overdueCount = 0;

      for (const doc of snapshot.docs) {
        const lead = doc.data();

        // Mark as overdue
        batch.update(doc.ref, {
          slaStatus: 'overdue',
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        // Create overdue event
        const eventRef = doc.ref.collection('events').doc();
        batch.set(eventRef, {
          type: 'sla_overdue',
          description: `SLA deadline missed for ${lead.firstName} ${lead.lastName} (${lead.tier} lead)`,
          metadata: {
            tier: lead.tier,
            slaDeadline: lead.slaDeadline,
            productCategory: lead.productCategory,
          },
          createdBy: 'system',
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        // Create urgent alert task
        const taskRef = db.collection('tasks').doc();
        batch.set(taskRef, {
          leadId: doc.id,
          title: `⚠️ SLA OVERDUE: Contact ${lead.firstName} ${lead.lastName} immediately`,
          description: `This ${lead.tier} lead has exceeded their SLA deadline. Product: ${lead.productCategory}. Budget: ${lead.targetBudget}.`,
          type: 'follow_up',
          priority: 'urgent',
          status: 'pending',
          dueAt: admin.firestore.Timestamp.now(),
          dueDate: admin.firestore.Timestamp.now(),
          assignedTo: lead.assignedTo || '',
          isAutoGenerated: true,
          completedAt: null,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        overdueCount++;
      }

      await batch.commit();
      functions.logger.warn(`SLA check: Marked ${overdueCount} leads as overdue`);

      // TODO: Send email/SMS notifications for overdue leads
      // await sendOverdueNotifications(overdueLeads);

      return null;
    } catch (error) {
      functions.logger.error('SLA checker error:', error);
      return null;
    }
  });

/**
 * Scheduled function: SLA Warning Checker
 * Runs every 5 minutes. Sets slaStatus to 'warning' when 75% of SLA time has elapsed.
 */
export const slaWarningChecker = functions.pubsub
  .schedule('every 5 minutes')
  .timeZone('America/New_York')
  .onRun(async () => {
    const now = new Date();

    try {
      const snapshot = await db
        .collection('leads')
        .where('slaStatus', '==', 'ok')
        .where('contactedAt', '==', null)
        .get();

      if (snapshot.empty) return null;

      const batch = db.batch();
      let warningCount = 0;

      for (const doc of snapshot.docs) {
        const lead = doc.data();
        if (!lead.slaDeadline) continue;

        const deadline = lead.slaDeadline.toDate();
        const created = lead.createdAt?.toDate() || now;
        const totalMs = deadline.getTime() - created.getTime();
        const elapsedMs = now.getTime() - created.getTime();
        const percentElapsed = totalMs > 0 ? elapsedMs / totalMs : 1;

        if (percentElapsed >= 0.75) {
          batch.update(doc.ref, {
            slaStatus: 'warning',
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
          });
          warningCount++;
        }
      }

      if (warningCount > 0) {
        await batch.commit();
        functions.logger.info(`SLA warning: Set ${warningCount} leads to warning status`);
      }

      return null;
    } catch (error) {
      functions.logger.error('SLA warning checker error:', error);
      return null;
    }
  });
