// ─────────────────────────────────────────────────────────────
// Task Zod Schemas – Garage Auto Supplies CRM
// ─────────────────────────────────────────────────────────────

import { z } from 'zod';

/** Schema for creating or editing a Task */
export const taskFormSchema = z.object({
  leadId: z.string().min(1, 'Lead ID is required'),
  title: z
    .string()
    .min(1, 'Task title is required')
    .max(200, 'Title is too long'),
  description: z
    .string()
    .max(5000, 'Description is too long')
    .default(''),
  type: z.enum(['follow_up', 'call', 'email', 'quote', 'general'], {
    message: 'Invalid task type',
  }),
  priority: z.enum(['urgent', 'high', 'normal', 'low'], {
    message: 'Invalid priority',
  }),
  status: z
    .enum(['pending', 'in_progress', 'completed', 'cancelled'], {
      message: 'Invalid status',
    })
    .default('pending'),
  dueAt: z.coerce.date(),
  assignedTo: z.string().min(1, 'Assignee is required'),
  isAutoGenerated: z.boolean().default(false),
});

/** Full task document schema (includes server-generated fields) */
export const taskSchema = taskFormSchema.extend({
  id: z.string().min(1),
  completedAt: z.coerce.date().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export type TaskFormInput = z.input<typeof taskFormSchema>;
export type TaskFormOutput = z.output<typeof taskFormSchema>;
export type TaskInput = z.input<typeof taskSchema>;
export type TaskOutput = z.output<typeof taskSchema>;
